import { useState, useEffect } from 'react'
import Head from 'next/head'
import { useRouter } from "next/router"

import BottomMenuBar from "../../../../components/BottomMenuBar"
import animapuApi from "../../../../apis/AnimapuApi"

var onApiCall = false
var onApiCall2 = false
var BreakException = {}
export default function ReadManga() {
  let router = useRouter()

  const query = router.query
  var manga_id = query.id
  var secondary_source_id = query.secondary_source_id
  var chapter_id = query.chapter_id
  const [manga, setManga] = useState({
    cover_image:[{image_urls:["/images/default-book.png"]}], chapters:[]
  })
  const [chapter, setChapter] = useState({chapter_images:[]})

  async function GetMangaDetail() {
    if (onApiCall) {return}
    onApiCall = true
    try {
      const response = await animapuApi.GetMangaDetail({
        manga_source: animapuApi.GetActiveMangaSource(),
        manga_id: manga_id,
        secondary_source_id: secondary_source_id
      })
      const body = await response.json()
      setManga(body.data)
      console.log(body)
      onApiCall = false

    } catch (e) {
      console.log(e)
      onApiCall = false
    }
  }
  async function GetReadManga() {
    if (onApiCall2) {return}
    onApiCall2 = true
    try {
      const response = await animapuApi.GetReadManga({
        manga_source: animapuApi.GetActiveMangaSource(),
        manga_id: manga_id,
        chapter_id: chapter_id,
        secondary_source_id: secondary_source_id
      })
      const body = await response.json()
      setChapter(body.data)
      console.log(body)
      onApiCall2 = false

    } catch (e) {
      console.log(e)
      onApiCall2 = false
    }
  }

  useEffect(() => {
    if (!query) {return}
    GetMangaDetail()
    GetReadManga()
  // eslint-disable-next-line
  }, [query])

  var unsupportedTitles = []
  var hist = {}
  function handleImageFallback(imageObj, e) {
    var found = false
    var selectedImageUrl = ""

    try {
      imageObj.image_urls.forEach((imageUrl,idx) => {
        if (!hist[`${imageUrl}-${idx}`]) {
          hist[`${imageUrl}-${idx}`] = true
          found = true
          selectedImageUrl = imageUrl
          throw BreakException
        }
      })
    } catch(err) {
      if (err !== BreakException) throw err

      if (found) {
        console.log(selectedImageUrl)
        e.target.src = selectedImageUrl
        return
      } else {
        e.target.style.display = "none"
      }
    }
    e.target.style.display = "none"

  }

  return (
    <div className="bg-[#d6e0ef]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>

        <div className="container mx-auto pt-1 px-1 max-w-[1040px]">
          <div className="mb-2">
            <span className="bg-white rounded p-1">Chapter {chapter.number}</span>
          </div>
          {chapter.chapter_images.map((imageObj, idx) => (
            <div key={`${chapter.id}-${idx}`}>
              <img
                className="w-full mb-1"
                src={imageObj.image_urls[0]}
                onError={(e) => handleImageFallback(imageObj, e)}
                alt="thumb"
              />
            </div>
          ))}
        </div>
      </div>

      <BottomMenuBar isPaginateNavOn={true} manga={manga} chapter_id={chapter_id} />
    </div>
  )
}
